server:
  port: 7002
spring:
  application:
    name: crayyge7001.com
eureka:
  client:
    service-url:
      defaultZone:  http://eureka1.com:8001/eureka/,http://eureka2.com:8002/eureka/,http://eureka3.com:8003/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: www.crayysge72.com